
on:
  release:
    types: [ created ]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        target: [ x86_64-pc-windows-gnu ]
    steps:
      - uses: actions/checkout@master
      - name: Compile & release
        uses: rust-build/rust-build.action@v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          TOOLCHAIN_VERSION: 1.72.0
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE digital_screen_image_display.e2"
